### ISSUE TITLE
Fix failing build due to Dashboard 2.0

### ISSUE THREAD

**Issue by joewiz** [eXist-db/e2e-core#8]
As the result of switching to Dashboard 2.0 in develop ([#2423](https://github.com/eXist-db/exist/pull/2423)) and develop-5.0.0 ([#2438](https://github.com/eXist-db/exist/pull/2438)), the tests in [dashboard_spec.js](https://github.com/eXist-db/e2e-core/blob/master/cypress/integration/dashboard_spec.js) and [users_spec.js](https://github.com/eXist-db/e2e-core/blob/master/cypress/integration/users_spec.js) now fail. 

For the failed test runs, see https://travis-ci.com/eXist-db/e2e-core/jobs/187293781 and https://dashboard.cypress.io/#/projects/w23pgu/runs/83/specs.

To fix the failing tests, I believe we need to account for the following changes:

- URL and HTML structure of resources within Dashboard have changed with 2.0.
- Dashboard's Collection browser has been removed in 2.0. 
- User Manager is a pane within Dashboard 2.0, so User Manager is no longer installed as a separate app bundled with eXist. 

Also, please bear in mind that the PRs above switching eXist to Dashboard 2.0 affect only the 5.x branches, and the 4.x branch is not (yet) affected. (I say "yet" because we've discussed the idea of switching 4.x to Dashboard 2.0 assuming we encounter no major issues under 5.x. This is an attractive idea given that Dashboard 1.x has many known bugs and is no longer maintained. So for the users who must stay on 4.x, Dashboard 2.0 should be a major improvement.)

@duncdrum I would greatly appreciate any help you might be able to provide with this!

**Comment by duncdrum** [comment]
@joewiz see #1, over here we can have a minimal test for dashboard by mimicking the existing test for package-manager. 

Unless there are problems with our sauce-lab account, @JoernT  and @windauer have implemented their own integration tests for polymer2 apps, you ll have to ask them.

**Comment by joewiz** [comment]
@duncdrum Thanks for the pointers. Since cypress.io can't access the shadow dom for tests, am I right that the "minimal test" you're suggesting would be limited to checking for, say, a 200 response to a request for the landing page?

@JoernT @windauer Could you point me to the integration tests you've implemented for Dashboard?

**Comment by joewiz** [comment]
@JoernT @windauer I've put Dashboard 2.0 on the agenda for tomorrow's community call, so if you're available, that could be a good opportunity to discuss any last issues before Dashboard 2.0 is included in the next eXist 5.x RC.

**Comment by JoernT** [comment]
I do not have any tests for the dashboard apps. Yes, that's a shame but results from the fact that i started early with Web Components where technologies were still in flux and i lacked time to work into the WCT back then. Building the apps was a hell lot of work and i was happy to get through anyway. 

However of course would be great to add them. WCT btw works fine and of course with ShadowDOM support and there's a script to run them from commandline (e.g. for Jenkins integration). The recipe is found in tei-publisher [repo](https://gitlab.existsolutions.com/tei-publisher/tei-publisher-app/tree/master/components/test/).

**Comment by joewiz** [comment]
@JoernT Thanks for letting us know!
